[local]
localhost

[mongodb]
localhost

[mysql]
localhost

[rabbitmq]
localhost

[redis]
localhost

[catalogue]
localhost

[frontend]
localhost

[user]
localhost

[cart]
localhost

[payment]
localhost

[shipping]
localhost

[dispatch]
localhost

[frontend]
localhost



# [local]
# localhost

# [mongodb]
# mongodb.devopspractice.online

# [mysql]
# mysql.devopspractice.online

# [rabbitmq]
# rabbitmq.devopspractice.online

# [redis]
# redis.devopspractice.online

# [catalogue]
# catalogue.devopspractice.online

# [frontend]
# frontend.devopspractice.online

# [user]
# user.devopspractice.online

# [cart]
# cart.devopspractice.online

# [payment]
# payment.devopspractice.online

# [shipping]
# shipping.devopspractice.online

# [dispatch]
# dispatch.devopspractice.online

# [frontend]
# frontend.devopspractice.online
